version: '3.8'

  #LARAVEL (PHP 8.2) ile NGINC kurulumu
services:
    # PHP Service
    laravel_10:
      build:
        context: ./project
        dockerfile: ../php/Dockerfile
      image: laravel_10
      container_name: laravel_10
      tty: true
      working_dir: /var/www
      volumes:
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        - ./project/:/var/www
      networks:
        - local-bridge

    # NGINX Service
    nginx:
      image: nginx:alpine
      container_name: nginx
      tty: true
      volumes:
        - ./project/:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
      ports:
        - 80:80
      networks:
        - local-bridge
      

    # MYSQL Service
    mysql_database:
      image: mysql:8.0
      container_name: mysql_container
      restart: always
      environment:
        MYSQL_DATABASE: docker-test
        MYSQL_USER: 'ufuk'
        MYSQL_PASSWORD:
        MYSQL_ROOT_PASSWORD:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      volumes:
        - ./database/mysql/mysql_8_1_0_data:/var/lib/mysql
      networks:
        - local-bridge
          

networks:
  local-bridge:
    driver: bridge




















